repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 0f86793af5ef5f6dc63c8d04a3cabfa3ea8f9c6a  # frozen: v1.16.1
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: '0b19ef1fd6ad680ed7752d6daba883ce1265a6de'  # frozen: v0.12.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
