repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: '0c7b6c989466a93942def1f84baf36ddfcd60c83'  # frozen: v0.15.14
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
