repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 8e5c80792e2ec0c87804d8ef915bf35e2caea6da  # frozen: v1.20.0
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'c60c980e561ed3e73101667fe8365c609d19a438'  # frozen: v0.15.9
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
