version: 2
formats: all
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
    - python -m pip install --constraint=.github/github-requirements.txt poetry
    - poetry config virtualenvs.create false
    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs --no-interaction
sphinx:
  configuration: docs/conf.py
