version: 2
formats: all
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
    - python -m pip install --constraint=.github/constraints.txt poetry
    - poetry config virtualenvs.create false
    post_install:
    - poetry install --with docs
sphinx:
  configuration: docs/conf.py
